/* 秋招网申自动填充助手 AI 厂商注册表 v1.8.0 */
globalThis.QIUZHAO_AI_PROVIDERS = Object.freeze([
  {
    id: 'openai',
    name: 'OpenAI',
    protocol: 'responses',
    auth: 'bearer',
    modelsEndpoint: 'https://api.openai.com/v1/models',
    chatEndpoint: 'https://api.openai.com/v1/responses',
    preferredModelPrefixes: ['gpt-5', 'gpt-4.1', 'gpt-4o'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    protocol: 'anthropic',
    auth: 'anthropic',
    modelsEndpoint: 'https://api.anthropic.com/v1/models?limit=1000',
    chatEndpoint: 'https://api.anthropic.com/v1/messages',
    preferredModelPrefixes: ['claude-sonnet', 'claude-opus', 'claude-haiku'],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/models',
    chatEndpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
    preferredModelPrefixes: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://api.deepseek.com/models',
    chatEndpoint: 'https://api.deepseek.com/chat/completions',
    preferredModelPrefixes: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'qwen',
    name: '阿里云百炼与通义千问',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://dashscope.aliyuncs.com/api/v1/models?capabilities=TG&page_size=100',
    chatEndpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',
    fallbackModels: ['qwen-plus', 'qwen-turbo', 'qwen-max'],
    preferredModelPrefixes: ['qwen-plus', 'qwen-turbo', 'qwen-max', 'qwen'],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://api.moonshot.cn/v1/models',
    chatEndpoint: 'https://api.moonshot.cn/v1/chat/completions',
    preferredModelPrefixes: ['kimi-k2', 'moonshot-v1', 'kimi'],
  },
  {
    id: 'siliconflow',
    name: '硅基流动 SiliconFlow',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://api.siliconflow.cn/v1/models',
    chatEndpoint: 'https://api.siliconflow.cn/v1/chat/completions',
  },
  {
    id: 'minimax',
    name: 'MiniMax 国内',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://api.minimaxi.com/v1/models',
    chatEndpoint: 'https://api.minimaxi.com/v1/chat/completions',
    preferredModelPrefixes: ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-M2'],
  },
  {
    id: 'minimax_global',
    name: 'MiniMax 国际',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: 'https://api.minimax.io/v1/models',
    chatEndpoint: 'https://api.minimax.io/v1/chat/completions',
    preferredModelPrefixes: ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-M2'],
  },
  {
    id: 'custom',
    name: '自定义兼容接口',
    protocol: 'chat-completions',
    auth: 'bearer',
    modelsEndpoint: '',
    chatEndpoint: '',
  },
]);
